### ISSUE TITLE
array parsing problem

### ISSUE THREAD

**Issue by voidpp** [bernii/querystring-parser#13]
Hi, 
I have an object in javascript for example:

``` javascript
var filters = {
    module: ['name1', 'name2'],
    msg: 'something' 
};
```

I send an ajax request with jQuery and the serialized raw string will be 

```
filters[module][]=name1&filters[module][]=name2&filters[msg]=something
```

The parser will parse to this: 

```
{u'filters': {u'msg': u'something', u'module': {u'': [u'name1', u'name2']}}}
```

The "module" value is dict but should be an array.
Of course, if I remove the "[]" parts from the raw string, the dict turn into array, but as I mentioned the string is serialized by the jQuery, not me.

**Comment by paulmelnikow** [comment]
This behavior was added in #24. To turn it on, pass `normalized=True` to the `parse()` function.
