### ISSUE TITLE
Error parsing QueryDict when html text input's name attribute contains word "column" 

### ISSUE THREAD

**Issue by patrickzurek** [bernii/querystring-parser#26]
The following HTML causes an error when the name attribute contains the word 'column' in it:  
`<input type="text" class="form-control column-class" placeholder="Column System Name" name="column[{{forloop.counter0}}][system]"/>`

My form method is POST.  The error I receive from querystring-parser after doing 

> post_in = parser.parse(request.POST.urlencode())

is:

> 'unicode' object does not support item assignment
> Line 162.                        tempdict[k] = v 

If I simply rename the name attribute to something like 

> name="XXXcolumn[{{forloop.counter0}}][system]"

it works fine.  Searching the web did not turn up anything about 'column' being a reserved keyword in HTML POSTs.

I also attempted to extract the value from the QueryDict in Django with the name attribute containing the original wording with 'column' in it prior to passing it to parser.parse like so:

> logger.debug("From post:" + request.POST.get("column[5][system]"))

and it correctly outputs the value.

It's trivial for me to rename the attribute name, but I wanted to bring this to your attention.  Hope it helps.  If this was an error on my part, then I apologize.  BTW, thanks for making this tool.

PS: I'm using python 2.7.6 and Django 1.8 and the latest version of querystring-parser.

**Comment by paulmelnikow** [comment]
@patrickzurek This is an old issue, but I'd be happy to patch it. Would need a little more info though. Can you print out the value of `request.POST.urlencode()` and post it here?

I can't reproduce this issue in a unit test.
