### ISSUE TITLE
adding querystring-parser to conda-forge

### ISSUE THREAD

**Issue by jaroslawk** [bernii/querystring-parser#30]
@bernii 

I would like to add your lit to conda-forge environment since it is being used by MLFlow and need to have it in conda.

Do you have any concerns with this?
Can I add you as a supporter? 

here is my attempt:
https://github.com/conda-forge/staged-recipes/pull/8102

**Comment by paulmelnikow** [comment]
I'm a co-maintainer here and I'm pretty new to conda, though happy to be listed as well.

**Comment by jaroslawk** [comment]
@paulmelnikow perfect. thank you! 
One more item is required - Licence.
Can you point me to exact license file you are using?
Preferably it should be in the sources.

**Comment by paulmelnikow** [comment]
It's MIT license (see #9); it's noted at the end of the readme. I opened #31 to check it in.

**Comment by jaroslawk** [comment]
Ok perfect. This is all I need I guess. I will use it in the conda PR

**Comment by jaroslawk** [comment]
ok feedstok for querystring-parser works and ability to install using conda also.
https://github.com/conda-forge/querystring_parser-feedstock
