### ISSUE TITLE
Release for 1.2.4

### ISSUE THREAD

**Issue by acxz** [bernii/querystring-parser#36]
Thanks for creating this project! I maintain the ArchLinux package, [here](https://aur.archlinux.org/packages/python-querystring-parser/), for this project and we have been having some trouble using it. It would be create if you can create an updated release [here](https://github.com/bernii/querystring-parser/releases) so that I can update the ArchLinux package.

**Comment by bernii** [comment]
@acxz added you as a collaborator so you can control the process :) wanna release the new version?

**Comment by acxz** [comment]
Sure sounds good! Thanks!

**Comment by acxz** [comment]
I'll close this issue once I get the new release out.

**Comment by bernii** [comment]
Thanks @acxz! :)

**Comment by acxz** [comment]
New release has been made: https://github.com/bernii/querystring-parser/releases/tag/1.2.4
