### ISSUE TITLE
Can't install version 1.2.4 on mac

### ISSUE THREAD

**Issue by nadavaviv** [bernii/querystring-parser#37]
I'm having a bit of trouble to locally install 1.2.4 on my mac.
Whenever I execute setup.py I get the following message:
```
/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

I want to upload this package to a private repo (s3pypi), so I have to install it like this, what can I do?
Thanks :)

**Comment by acxz** [comment]
Hey @nadavaviv can you post the exact command you ran?

**Comment by nadavaviv** [comment]
python3 setup.py

**Comment by acxz** [comment]
Can you `python setup.py build` and post the output of that.
And then do `python setup.py install` and post the output of that.

**Comment by acxz** [comment]
Usually when you use `pip` you can just do `pip install .` where `.` refers to the directory where the setup.py is installed. But if just want to use `setup.py` without `pip`. You need to specify `build` and `install`.

Effectively `python setup.py build && python setup.py install` is the same as `pip install .`

**Comment by nadavaviv** [comment]
Gotcha, Probably not you're issue but I'll try anyway...

Do you have any idea how I can upload it to s3pypi?

**Comment by acxz** [comment]
I do not know what s3pypi is.

**Comment by nadavaviv** [comment]
Gotcha, Thanks :)
