### ISSUE TITLE
library does not provide a .whl wheel distribution

### ISSUE THREAD

**Issue by chrisantonellis** [bernii/querystring-parser#39]
this library does not provide a `.whl` distribution

pythonwheels.com provides instructions on how to implement the building of `.whl` distributions alongside `sdist` distributions

addressed by this PR: https://github.com/bernii/querystring-parser/pull/38

can the `hacktoberfest` label be added to this issue so I can get credit for the contribution? Thank You!

**Comment by chrisantonellis** [comment]
@bernii any interest in this PR? Thanks!

**Comment by paulmelnikow** [comment]
The v1.2.4 wheel has been published 🚀 

Thanks!
