### ISSUE TITLE
Parse Arrays as Arrays instead of Dictionaries

### ISSUE THREAD

**Issue by lylepratt** [bernii/querystring-parser#4]
Currently if you have a form name such as: `example[0]['test']` you get back this from querystring-parser:

```
{
    "example": {
        "0": {
            "test": "fest"
        }
    }
}
```

It would be much better if it returned this instead:

```
{
    "example": [
        {
            "test": "fest"
        }
    ]
}
```

This isn't a HUGE issue, but its fairly annoying. If I get some time, I'll submit a pull request to solve this.

**Comment by paulmelnikow** [comment]
This behavior was added in #24. To turn it on, pass `normalized=True` to the `parse()` function.
