### ISSUE TITLE
Fails parsing a query string

### ISSUE THREAD

**Issue by sn0rcha** [bernii/querystring-parser#6]
Hey there,

I'm getting the following error when trying to parse:

http://192.168.178.150:8000/ads/kendo/?template=ads/ajax/json/list_ads_kendo.html&ca=1&filter%5Bfilters%5D%5B99%5D%5Bfield%5D=transferred&filter%5Bfilters%5D%5B99%5D%5Boperator%5D=eq&filter%5Bfilters%5D%5B99%5D%5Bvalue%5D=0&take=100&skip=0&page=1&pageSize=100&sort%5B0%5D%5Bfield%5D=created&sort%5B0%5D%5Bdir%5D=desc&filter=

Using:

arguments = parser.parse(request.GET.urlencode())

I get the following error:

"list indices must be integers, not unicode"

If I remove the last "&filter=" - it parses no problems.

Any ideas?

**Comment by paulmelnikow** [comment]
Hmm, this doesn't seem to be a problem with this library. I'm not able to reproduce it using a test case.

You could try using [`request.META['QUERY_STRING']`](https://docs.djangoproject.com/en/1.10/ref/request-response/#django.http.HttpRequest.META) in place of `request.GET.urlencode()`. Maybe that will be more reliable.
